### ISSUE TITLE
Keypad does not work on doors nor plays sound

### ISSUE THREAD

**Issue by chsterz** [workadventure/scripting-api-extra#116]
Here is the error: 
```
TypeError: Cannot read properties of undefined (reading 'entries')
    at Proxy.initVariables (state.ts:49:48)
    at iframe_api.ts:38:18
```
I am running a fairly old Workadventure, ~Nov 2021

I debugged in a bit. It seems, that the `WA.onInit()`call returns `undefined` instead of a valid Promise.
This causes the catch block around it to directly fire and hinders the preparation of the Keypad. 
The Keypad shows up, but no key-sounds are played nor the door opens like it did before (worked on 5th of Jan still, can confirm)

![Screenshot from 2022-01-26 11-55-27](https://user-images.githubusercontent.com/315665/151151984-bab35f30-861e-430c-9be1-ff60cdcacbaa.png)

I tried forcing the version of scripting-api-extra to 1.1.1 which was available at 5th of Jan when it still worked, but it still gave the same error on my instance.

**Comment by gparant** [comment]
ping @moufmouf
